<script>
    export let isPreview
    export let isPost
    import { postParsedWeather, preParsedWeather, options} from "../store"


</script>

<div class="weatherDisp" class:results-preview={isPreview}>
    {#if isPreview}<h3>Preview:</h3>{/if}

    {#if $options.icon}
      {#if isPost}
        {#if $options.iconType === 'open'}
          {@html $postParsedWeather.icon.open}
        {:else if $options.iconType === 'emoji'}
          {$postParsedWeather.icon.emoji}
        {/if}
      {:else}
        {#if $options.iconType === 'open'}
          {@html $preParsedWeather.icon.open}
        {:else if $options.iconType === 'emoji'}
          {$preParsedWeather.icon.emoji}
        {/if}
      {/if}
    {/if}

    {#if $options.conditions}
      <p>
        {#if isPost}
          {$postParsedWeather.conditions}
        {:else}
          {$preParsedWeather.conditions}
        {/if}
      </p>
    {/if}

    {#if $options.temperature}
      <p>Temperature: 
        {#if isPost}
          {$options.temperatureUnit === 'c' ? $postParsedWeather.temperature.c : $postParsedWeather.temperature.f}
        {:else}
          {$options.temperatureUnit === 'c' ? $preParsedWeather.temperature.c : $preParsedWeather.temperature.f}
        {/if}
      </p>
    {/if}

    {#if $options.windspeed}
      <p>Wind: 
        {#if isPost}
          {#if $options.windUnit === 'description'}
            {$postParsedWeather.windspeed.description}
          {:else if $options.windUnit === 'beaufort'}
            Beaufort force {$postParsedWeather.windspeed.beaufort}
          {:else if $options.windUnit === 'mph'}
            {$postParsedWeather.windspeed.mph}
          {:else if $options.windUnit === 'kmh'}
            {$postParsedWeather.windspeed.kmh}
          {:else if $options.windUnit === 'ms'}
            {$postParsedWeather.windspeed.ms}
          {/if}
<!-- 
          {#if $options.windDirection} 
            {#if $options.windDirectionType === 'arrow'}
              {$postParsedWeather.windDirection.arrow}
            {:else if $options.windDirectionType === 'text'}
              {$postParsedWeather.windDirection.text}
            {/if}
          {/if} -->

        {:else}
          {#if $options.windUnit === 'description'}
            {$preParsedWeather.windspeed.description}
          {:else if $options.windUnit === 'beaufort'}
            Beaufort force {$preParsedWeather.windspeed.beaufort}
          {:else if $options.windUnit === 'mph'}
            {$preParsedWeather.windspeed.mph}
          {:else if $options.windUnit === 'kmh'}
            {$preParsedWeather.windspeed.kmh}
          {:else if $options.windUnit === 'ms'}
            {$preParsedWeather.windspeed.ms}
          {/if}

          <!-- {#if $options.windDirection} 
            {#if $options.windDirectionType === 'arrow'}
              {$preParsedWeather.windDirection.arrow}
            {:else if $options.windDirectionType === 'text'}
              {$preParsedWeather.windDirection.text}
            {/if}
          {/if} -->
        {/if}
      </p>
    {/if}

    {#if $options.windDirection}
      <p>Wind Direction: 
        {#if isPost}
          {#if $options.windDirectionType === 'arrow'}
            {$postParsedWeather.windDirection.arrow}
          {:else if $options.windDirectionType === 'text'}
            {$postParsedWeather.windDirection.text}
          {/if}
        {:else}
          {#if $options.windDirectionType === 'arrow'}
            {$preParsedWeather.windDirection.arrow}
          {:else if $options.windDirectionType === 'text'}
            {$preParsedWeather.windDirection.text}
          {/if}
        {/if}
      </p>
    {/if}

    {#if $options.cloudCover}
      <p>Cloud Cover: 
        {#if isPost}
          {$postParsedWeather.cloudCover}%
        {:else}
          {$preParsedWeather.cloudCover}%
        {/if}
      </p>
    {/if}

    {#if $options.humidity}
      <p>Humidity: 
        {#if isPost}
          {$postParsedWeather.humidity}%
        {:else}
          {$preParsedWeather.humidity}%
        {/if}
      </p>
    {/if}

    {#if $options.sunrise}
      <p>Sunrise: 
        {#if isPost}
          {$postParsedWeather.sunrise}
        {:else}
          {$preParsedWeather.sunrise}
        {/if}
      </p>
    {/if}

    {#if $options.sunset}
      <p>Sunset: 
        {#if isPost}
          {$postParsedWeather.sunset}
        {:else}
          {$preParsedWeather.sunset}
        {/if}
      </p>
    {/if}

    {#if $options.attr}
      Weather generated by <a href="https://raincrow.netlify.app/" target="_blank">RainCrow</a>
    {/if}

    
  </div>

  <style>
    .results-preview {
      font-size: 0.75rem;
      margin: auto;
      min-height: 220px;
      width: fit-content;
    }
  </style>